### ISSUE TITLE
Multiple moves made during training

### ISSUE THREAD

**Issue by barrybecker4** [maxpumperla/ScalphaGoZero#14]
#### Issue Description

When I printed the board during training, I couldn't understand why selectMove was producing a board with multiple same player moves. After debugging, I found that it was caused by all the mutable state inside the GoBoard class. I found that the problem went away when I made everything immutable. So for example, GoBoard.placeStone creates a new immutable GoBoard rather than modifying the current one. I will make a PR shortly.

**Comment by maxpumperla** [comment]
@barrybecker4 thanks again for your contribution!
