### ISSUE TITLE
bug in ZeroEncoder

### ISSUE THREAD

**Issue by barrybecker4** [maxpumperla/ScalphaGoZero#16]
I was adding unit tests for the ZeroEncoder class, and noticed what I believe is a bug.
I believe that his line
`var libertyPlane = Math.max(Math.min(4, string.numLiberties) - 1, 1)`
should be
`var libertyPlane = Math.max(Math.min(4, string.numLiberties) - 1, 0)` 
or just 
`var libertyPlane =Math.min(4, string.numLiberties) - 1` 
since a string can never have 0 liberties.

Without this change the 0th ( and 4th) planes will always be all 0. Points with only 1 liberty will get treated like they have 2.

I have been making a lot of changes in my fork to add features and fix issues without doing a lot of separate pull requests. Maybe I will do just one big PR when I am done. Not sure what will be the best way to manage it. In any case, I am really grateful for this project and the accompanying book.

**Comment by maxpumperla** [comment]
@barrybecker4 thanks for your comments, I think you're right. Looking forward to fixes in any way, shape or form - as long as you don't turn everything upside down to make a review impossible ;)

**Comment by barrybecker4** [comment]
This was fixed and merged a long time ago.
See https://github.com/barrybecker4/ScalphaGoZero/issues/12
for more info.
